# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build & Tests

on:
  # 支持手动触发构建
  workflow_dispatch:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "Set up JDK"
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'adopt'
          cache: maven
          server-id: carm-repo
          server-username: MAVEN_USERNAME
          server-password: MAVEN_TOKEN

      - name: "Package"
        run: mvn -B package --file pom.xml

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: "**/target/"
          retention-days: 1

      - name: "Upload assets"
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: ".asset/*.jar"
          retention-days: 5
          include-hidden-files: true